### ISSUE TITLE
Does original NeRF work in your experiment?

### ISSUE THREAD

**Issue by riven314** [tancik/learnit#9]
Thanks for releasing the JAX based code! I am trying to use your NeRF implementation as a base to implement DietNeRF (in JAX and Haiku). But I noticed your implementation has 2 differences with the original one, as stated in your paper:  

> In our view synthesis experiments, we use a simplified NeRF model (simple-NeRF) that maintains the same image supervision and volume render-ing context.   Unlike the original NeRF model,  we do not feed in the viewing direction and we use a single model in-stead of the two “coarse” and “fine” models used by NeRF.

Would you mind telling me the motivation behind this simplification?  
(e.g. Is it because the original NeRF didnt work in your setting? or because its easier to implement this in JAX?) Knowing this may help me to debug my DietNeRF implementation in the future. Many thanks!

**Comment by tancik** [comment]
Great question. The choice of using a simplified model was primarily out of convenience. The decided to skip view dependence in our experiments because the shapenet dataset is lambertian and it is unclear if it would be possible to disentangle non-lambertain effects from general appearance variation in the phototourism data (since multi-view data under the same lighting conditions is not available). We focused on a single "coarse" model because of the computational overhead of meta-learning. I can't think of any specific reason why the method would fail if a coarse-fine hierarchy is utilized. There are some recent full nerf models implemented in JAX that may be of interest to you - [JaxNeRF](https://github.com/google-research/google-research/tree/master/jaxnerf), [mipNeRF](https://github.com/google/mipnerf), [nerfies](https://github.com/google/nerfies)

**Comment by riven314** [comment]
@tancik 
wow! Thanks for the pointers. (They didnt appear in my radar)
They are really great reference Thanks a lot!
